name: Attack Surface Detection

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  detect-attack-surface:
    name: Run OWASP Noir (Attack Surface Detector)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Projeye göre 8, 11, 17 seçebilirsin

      - name: Download Noir Attack Surface Detector CLI
        run: |
          wget https://github.com/OWASP/ASD/releases/latest/download/attack-surface-detector-cli.jar -O noir-cli.jar

      - name: Run Noir on the source code
        run: |
          mkdir output
          java -jar noir-cli.jar ./ -o ./output/endpoints.json

      - name: Show detected endpoints
        run: |
          echo "== Detected Endpoints =="
          cat ./output/endpoints.json
